export const SEARCH_GAME = "SEARCH_GAME";
export const SET_GAME = "SET_GAME";
export const SET_PAGINATION = "SET_PAGINATION";
export const SET_PAGE_LOADING = "SET_PAGE_LOADING";
export const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
export const SET_GAME_DETAIL = "SET_GAME_DETAIL";

export const CLEAR_GAME_DETAIL = "CLEAR_GAME_DETAIL";
